apiDefinitions:
  main: ./openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
    no-ambiguous-paths: off
referenceDocs:
  htmlTemplate: ./docs/index.html
  showConsole: true
